# Generated by Django 5.0.3 on 2024-03-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airlineName', models.CharField(max_length=255)),
                ('flightId', models.IntegerField()),
                ('price', models.FloatField()),
                ('flightNumber', models.IntegerField()),
                ('originAirportCode', models.IntegerField()),
                ('destinationAirportCode', models.IntegerField()),
                ('availableSeats', models.IntegerField()),
                ('departureDateTime', models.DateField()),
                ('arrivalDateTime', models.DateField()),
            ],
            options={
                'ordering': ['airlineName'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=255)),
                ('hotelId', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('stars', models.IntegerField()),
                ('pricePerDay', models.FloatField()),
                ('checkinTime', models.DateField()),
                ('checkoutTime', models.DateField()),
            ],
            options={
                'ordering': ['hotelName'],
            },
        ),
    ]
