# Generated by Django 3.2.5 on 2024-04-12 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpackage',
            name='nbr_adult',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='nbr_child',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='paymentState',
            field=models.CharField(choices=[('First_Deposit', 'FIRST_DEPOSIT'), ('Second_Deposit', 'SECOND_DEPOSIT'), ('Last_Deposit', 'LAST_DEPOSIT')], max_length=255),
        ),
        migrations.AlterField(
            model_name='billing',
            name='paymentType',
            field=models.CharField(choices=[('Visa', 'VISA'), ('Mastercard', 'MASTERCARD'), ('Paypal', 'PAYPAL'), ('Stripe', 'STRIPE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingState',
            field=models.CharField(choices=[('Created', 'CREATED'), ('Processing', 'PROCESSING'), ('Canceled', 'CANCELED'), ('Failed', 'FAILED'), ('Modified', 'MODIFIED'), ('Confirmed', 'CONFIRMED'), ('Refunded', 'REFUNDED')], default='CREATED', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nbr_adult',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='nbr_child',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]