# Generated by Django 5.0.3 on 2024-03-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['airlinename']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['hotelname']},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airlineName',
            new_name='airlinename',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='arrivalDateTime',
            new_name='arrivaldatetime',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='availableSeats',
            new_name='availableseats',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departureDateTime',
            new_name='departuredatetime',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flightId',
            new_name='flightid',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flightNumber',
            new_name='flightnumber',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='checkinTime',
            new_name='checkintime',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='checkoutTime',
            new_name='checkouttime',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelId',
            new_name='hotelid',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelName',
            new_name='hotelname',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='pricePerDay',
            new_name='priceperday',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destinationAirportCode',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='originAirportCode',
        ),
        migrations.AddField(
            model_name='flight',
            name='destinationairport',
            field=models.CharField(default='london', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='originairport',
            field=models.CharField(default='montreal', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('grade', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('activity', models.ManyToManyField(null=True, to='flyapp.activity')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.flight')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.hotel')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
