# Generated by Django 5.0.3 on 2024-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0002_alter_flight_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.IntegerField(unique=True)),
                ('customer', models.CharField(max_length=255)),
                ('totalcost', models.FloatField()),
                ('details', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('checked', 'CHECKED')], default='CREATED', max_length=255)),
                ('package', models.ManyToManyField(to='flyapp.package')),
            ],
            options={
                'ordering': ['bookingid'],
            },
        ),
    ]
