# Generated by Django 3.2.5 on 2024-04-12 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0002_auto_20240412_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='nbr_adult',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='nbr_child',
        ),
    ]
