# Generated by Django 3.2.5 on 2024-04-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0003_auto_20240412_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='user',
        ),
    ]
