# Generated by Django 5.0.1 on 2024-03-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0004_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='flyapp.activity'),
        ),
    ]
