# Generated by Django 5.0.3 on 2024-04-12 12:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0004_remove_travelpackage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='nbr_adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='nbr_child',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='nbr_adult',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='nbr_child',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userpkg', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='paymentState',
            field=models.CharField(choices=[('firstdeposit', 'FIRSTDEPOSIT'), ('seconddeposit', 'SECONDDEPOSIT'), ('lastdeposit', 'LASTDEPOSIT')], max_length=255),
        ),
        migrations.AlterField(
            model_name='billing',
            name='paymentType',
            field=models.CharField(choices=[('visa', 'VISA'), ('paypal', 'PAYPAL')], max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bookingState',
            field=models.CharField(choices=[('created', 'CREATED'), ('processing', 'PROCESSING'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('modified', 'MODIFIED'), ('confirmed', 'CONFIRMED'), ('refunded', 'REFUNDED')], default='CREATED', max_length=255),
        ),
    ]
