# Generated by Django 5.0.3 on 2024-04-12 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0005_remove_booking_nbr_adult_remove_booking_nbr_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='nbr_adult',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='nbr_child',
        ),
        migrations.AddField(
            model_name='booking',
            name='nbr_adult',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='nbr_child',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
