# Generated by Django 5.0.3 on 2024-04-12 20:08

import flyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0006_remove_travelpackage_nbr_adult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='showDetails',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='showDetails',
        ),
        migrations.RemoveField(
            model_name='hotelbooking',
            name='showDetails',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='showDetails',
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='activity',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='photos',
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to=flyapp.models.photo_upload_to),
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.ManyToManyField(blank=True, to='flyapp.photo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(blank=True, to='flyapp.photo'),
        ),
    ]
