# Generated by Django 3.2.5 on 2024-04-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0007_remove_activity_showdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
