# Generated by Django 5.0.1 on 2024-03-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0007_alter_package_flight_alter_package_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('created', 'CREATED'), ('pending', 'PENDING'), ('canceled', 'CANCELED'), ('modified', 'MODIFIED'), ('checked', 'CHECKED')], default='CREATED', max_length=255),
        ),
    ]
