# Generated by Django 5.0.3 on 2024-04-15 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0007_remove_activity_showdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.billing'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='flyapp.photo'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='type',
            field=models.CharField(blank=True, choices=[('pre-made', 'PRE-MADE'), ('custom', 'CUSTOM')], default='PRE-MADE', max_length=255),
        ),
    ]
