# Generated by Django 5.0.3 on 2024-04-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0008_auto_20240413_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='John', max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=150, verbose_name='last name'),
        ),
    ]
