# Generated by Django 5.0.3 on 2024-04-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0008_auto_20240413_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.billing'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='John', max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='Doe', max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='photos', to='flyapp.photo'),
        ),
    ]
