# Generated by Django 5.0.1 on 2024-03-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0008_alter_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agent', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('pending', 'PENDING'), ('rejected', 'REJECTED'), ('accepted', 'ACCEPTED')], default='PENDING', max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('activity', models.ManyToManyField(blank=True, to='flyapp.activity')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flyapp.flight')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flyapp.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.package')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
