# Generated by Django 5.0.3 on 2024-04-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0008_auto_20240413_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
