# Generated by Django 5.0.1 on 2024-03-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0009_packagemodification'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodification',
            name='booking_cancellation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
