# Generated by Django 5.0.3 on 2024-03-24 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0010_packagemodification_booking_cancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='creationdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrivaldatetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departuredatetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='package',
            name='grade',
            field=models.CharField(choices=[('pre-made', 'PRE-MADE'), ('custom', 'CUSTOM')], max_length=255),
        ),
    ]
