# Generated by Django 5.0.3 on 2024-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0012_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=255),
        ),
    ]
