# Generated by Django 5.0.3 on 2024-03-28 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0013_alter_package_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentType', models.CharField(choices=[('visa', 'VISA'), ('paypal', 'PAYPAL')], max_length=255)),
                ('paymentState', models.CharField(choices=[('firstdeposit', 'FIRSTDEPOSIT'), ('seconddeposit', 'SECONDDEPOSIT'), ('lastdeposit', 'LASTDEPOSIT')], max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('firstLineAddress', models.CharField(max_length=255)),
                ('secondLineAddress', models.CharField(max_length=255)),
                ('zipCode', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state_area', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['firstName'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='package',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['bookingNo']},
        ),
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': ['airline']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='bookingid',
            new_name='bookingNo',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='totalcost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='creationdate',
            new_name='purchaseDate',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='airlinename',
            new_name='airline',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destinationairport',
            new_name='arrivalAirport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='arrivaldatetime',
            new_name='arrivalDate',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='originairport',
            new_name='departureAirport',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departuredatetime',
            new_name='departureDate',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='availableseats',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='hotelname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='packagemodification',
            old_name='end',
            new_name='endingDate',
        ),
        migrations.RenameField(
            model_name='packagemodification',
            old_name='start',
            new_name='startingDate',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flightid',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='flightnumber',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkintime',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkouttime',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='hotelid',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='priceperday',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='stars',
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='location',
            field=models.CharField(default='london', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='showDetails',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='bookingState',
            field=models.CharField(choices=[('created', 'CREATED'), ('processing', 'PROCESSING'), ('canceled', 'CANCELED'), ('failed', 'FAILED'), ('modified', 'MODIFIED'), ('confirmed', 'CONFIRMED'), ('refunded', 'REFUNDED')], default='CREATED', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='montreal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='country',
            field=models.CharField(default='canada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default='me@admin.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='firstLineAddress',
            field=models.CharField(default='2050 Saint catherine', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='firstName',
            field=models.CharField(default='Jimmy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='lastName',
            field=models.CharField(default='Anderson', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(default='1234567890', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='secondLineAddress',
            field=models.CharField(default='MTL, QC', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='state_area',
            field=models.CharField(default='QC', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='zipCode',
            field=models.CharField(default='h4b 2oy', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='airlineLogo',
            field=models.CharField(default='URL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalCity',
            field=models.CharField(default='Tehran', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='arrivalCountry',
            field=models.CharField(default='IR', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(default='MTL', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departureCountry',
            field=models.CharField(default='Canada', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='showDetails',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name='packagemodification',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='packagemodification',
            name='hotel',
        ),
        migrations.AddField(
            model_name='booking',
            name='billing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flyapp.billing'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.FloatField()),
                ('checkIn', models.DateField()),
                ('checkOut', models.DateField()),
                ('showDetails', models.BooleanField(blank=True, default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.hotel')),
            ],
            options={
                'ordering': ['hotel'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flyapp.photo'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flyapp.photo'),
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='photos',
            field=models.ManyToManyField(blank=True, to='flyapp.photo'),
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('pre-made', 'PRE-MADE'), ('custom', 'CUSTOM')], default='CUSTOM', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('showDetails', models.BooleanField(blank=True, default=True)),
                ('nbr_adult', models.IntegerField()),
                ('nbr_child', models.IntegerField()),
                ('activity', models.ManyToManyField(blank=True, to='flyapp.activity')),
                ('flight', models.ManyToManyField(blank=True, to='flyapp.flight')),
                ('hotel', models.ManyToManyField(blank=True, to='flyapp.hotelbooking')),
                ('photos', models.ManyToManyField(blank=True, to='flyapp.photo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='travelPackage',
            field=models.ManyToManyField(to='flyapp.travelpackage'),
        ),
        migrations.AlterField(
            model_name='packagemodification',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.travelpackage'),
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='flight',
            field=models.ManyToManyField(blank=True, to='flyapp.flight'),
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='hotel',
            field=models.ManyToManyField(blank=True, to='flyapp.hotelbooking'),
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
