# Generated by Django 3.2.5 on 2024-03-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0014_billing_photo_remove_booking_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='details',
        ),
        migrations.AlterField(
            model_name='billing',
            name='secondLineAddress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='secondLineAddress',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
