# Generated by Django 3.2.5 on 2024-03-30 02:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0015_auto_20240329_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelpackage',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='travelpackage',
            name='hotel',
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='activities',
            field=models.ManyToManyField(blank=True, to='flyapp.Activity'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='flights',
            field=models.ManyToManyField(blank=True, to='flyapp.Flight'),
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='flyapp.HotelBooking'),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='nbr_adult',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='travelpackage',
            name='nbr_child',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
