# Generated by Django 3.2.5 on 2024-03-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0016_auto_20240329_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagemodification',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='packagemodification',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='packagemodification',
            name='hotel',
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='activities',
            field=models.ManyToManyField(blank=True, to='flyapp.Activity'),
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='flights',
            field=models.ManyToManyField(blank=True, to='flyapp.Flight'),
        ),
        migrations.AddField(
            model_name='packagemodification',
            name='hotels',
            field=models.ManyToManyField(blank=True, to='flyapp.HotelBooking'),
        ),
    ]
