# Generated by Django 5.0.3 on 2024-04-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0017_auto_20240329_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='photos',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(blank=True, to='flyapp.photo'),
        ),
    ]
