# Generated by Django 3.2.5 on 2024-04-05 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0017_auto_20240329_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travelPackage',
        ),
        migrations.AddField(
            model_name='booking',
            name='travelPackage',
            field=models.ForeignKey(default=666, on_delete=django.db.models.deletion.CASCADE, to='flyapp.travelpackage'),
            preserve_default=False,
        ),
    ]
