# Generated by Django 3.2.5 on 2024-04-05 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0018_auto_20240404_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travelPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='flyapp.travelpackage'),
        ),
    ]
