# Generated by Django 3.2.5 on 2024-04-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0019_alter_booking_travelpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='travelPackage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flyapp.travelpackage'),
        ),
    ]
