# Generated by Django 5.0.3 on 2024-04-04 20:13

import flyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0020_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.ImageField(upload_to=flyapp.models.photo_upload_to),
        ),
    ]
