# Generated by Django 3.2.5 on 2024-04-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0020_alter_booking_travelpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('payment_method_types', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('payment_intent', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('payment_method_details', models.CharField(max_length=255)),
                ('receipt_url', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
