# Generated by Django 5.0.3 on 2024-04-04 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0021_alter_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='upload_dir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
