# Generated by Django 3.2.5 on 2024-04-10 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0021_createpaymentintent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreatePaymentIntent',
        ),
    ]
