# Generated by Django 5.0.3 on 2024-04-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyapp', '0020_alter_booking_travelpackage'),
        ('flyapp', '0022_photo_upload_dir'),
    ]

    operations = [
    ]
